# Generated by Django 5.2.3 on 2025-06-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='modefied_date',
            new_name='modified_date',
        ),
    ]
